/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TypesRouteImport } from './routes/types'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as ApiDynamicRoutesRouteImport } from './routes/api/dynamic-routes'
import { Route as FSplatRouteImport } from './routes/f.$'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as SCodeRouteImport } from './routes/s.$code'
import { Route as AuthenticatedDashboardAnalyticsIdRouteImport } from './routes/_authenticated.dashboard.analytics.$id'
import { Route as ApiPublicOgCodeDotpngRouteImport } from './routes/api/public/og.$code[.]png'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesRoute = TypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiDynamicRoutesRoute = ApiDynamicRoutesRouteImport.update({
  id: '/api/dynamic-routes',
  path: '/api/dynamic-routes',
  getParentRoute: () => rootRouteImport,
} as any)
const FSplatRoute = FSplatRouteImport.update({
  id: '/f/$',
  path: '/f/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardAnalyticsIdRoute =
  AuthenticatedDashboardAnalyticsIdRouteImport.update({
    id: '/analytics/$id',
    path: '/analytics/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicOgCodeDotpngRoute = ApiPublicOgCodeDotpngRouteImport.update({
  id: '/api/public/og/$code.png',
  path: '/api/public/og/$code.png',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/convert': typeof ConvertRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner': typeof ScannerRoute
  '/support': typeof SupportRoute
  '/types': typeof TypesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/api/dynamic-routes': typeof ApiDynamicRoutesRoute
  '/f/$': typeof FSplatRoute
  '/r/$code': typeof RCodeRoute
  '/s/$code': typeof SCodeRoute
  '/dashboard/analytics/$id': typeof AuthenticatedDashboardAnalyticsIdRoute
  '/api/public/og/$code.png': typeof ApiPublicOgCodeDotpngRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/convert': typeof ConvertRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner': typeof ScannerRoute
  '/support': typeof SupportRoute
  '/types': typeof TypesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/api/dynamic-routes': typeof ApiDynamicRoutesRoute
  '/f/$': typeof FSplatRoute
  '/r/$code': typeof RCodeRoute
  '/s/$code': typeof SCodeRoute
  '/dashboard/analytics/$id': typeof AuthenticatedDashboardAnalyticsIdRoute
  '/api/public/og/$code.png': typeof ApiPublicOgCodeDotpngRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/convert': typeof ConvertRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner': typeof ScannerRoute
  '/support': typeof SupportRoute
  '/types': typeof TypesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/dynamic-routes': typeof ApiDynamicRoutesRoute
  '/f/$': typeof FSplatRoute
  '/r/$code': typeof RCodeRoute
  '/s/$code': typeof SCodeRoute
  '/_authenticated/dashboard/analytics/$id': typeof AuthenticatedDashboardAnalyticsIdRoute
  '/api/public/og/$code.png': typeof ApiPublicOgCodeDotpngRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compare'
    | '/convert'
    | '/pricing'
    | '/reset-password'
    | '/scanner'
    | '/support'
    | '/types'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/api/dynamic-routes'
    | '/f/$'
    | '/r/$code'
    | '/s/$code'
    | '/dashboard/analytics/$id'
    | '/api/public/og/$code.png'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compare'
    | '/convert'
    | '/pricing'
    | '/reset-password'
    | '/scanner'
    | '/support'
    | '/types'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/api/dynamic-routes'
    | '/f/$'
    | '/r/$code'
    | '/s/$code'
    | '/dashboard/analytics/$id'
    | '/api/public/og/$code.png'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/compare'
    | '/convert'
    | '/pricing'
    | '/reset-password'
    | '/scanner'
    | '/support'
    | '/types'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/api/dynamic-routes'
    | '/f/$'
    | '/r/$code'
    | '/s/$code'
    | '/_authenticated/dashboard/analytics/$id'
    | '/api/public/og/$code.png'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  ConvertRoute: typeof ConvertRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScannerRoute: typeof ScannerRoute
  SupportRoute: typeof SupportRoute
  TypesRoute: typeof TypesRoute
  ApiDynamicRoutesRoute: typeof ApiDynamicRoutesRoute
  FSplatRoute: typeof FSplatRoute
  RCodeRoute: typeof RCodeRoute
  SCodeRoute: typeof SCodeRoute
  ApiPublicOgCodeDotpngRoute: typeof ApiPublicOgCodeDotpngRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types': {
      id: '/types'
      path: '/types'
      fullPath: '/types'
      preLoaderRoute: typeof TypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/dynamic-routes': {
      id: '/api/dynamic-routes'
      path: '/api/dynamic-routes'
      fullPath: '/api/dynamic-routes'
      preLoaderRoute: typeof ApiDynamicRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$': {
      id: '/f/$'
      path: '/f/$'
      fullPath: '/f/$'
      preLoaderRoute: typeof FSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/analytics/$id': {
      id: '/_authenticated/dashboard/analytics/$id'
      path: '/analytics/$id'
      fullPath: '/dashboard/analytics/$id'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/og/$code.png': {
      id: '/api/public/og/$code.png'
      path: '/api/public/og/$code.png'
      fullPath: '/api/public/og/$code.png'
      preLoaderRoute: typeof ApiPublicOgCodeDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAnalyticsIdRoute: typeof AuthenticatedDashboardAnalyticsIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAnalyticsIdRoute:
      AuthenticatedDashboardAnalyticsIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  ConvertRoute: ConvertRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScannerRoute: ScannerRoute,
  SupportRoute: SupportRoute,
  TypesRoute: TypesRoute,
  ApiDynamicRoutesRoute: ApiDynamicRoutesRoute,
  FSplatRoute: FSplatRoute,
  RCodeRoute: RCodeRoute,
  SCodeRoute: SCodeRoute,
  ApiPublicOgCodeDotpngRoute: ApiPublicOgCodeDotpngRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
